### ISSUE TITLE
Incorrect entry and exit date/price upon signal generation

### ISSUE THREAD

**Issue by ven7782** [russs123/double7#1]
```
if row[f"{s}_Signal"] == True:
    entry_date = i
    entry_price = row.Open
```

If a signal is generated, the entry date is the current date and price is open price of current date. Shouldn't it be the open price of the next day?

```
entry_date = df.index[i + 1]  # Entry date is the next row's index (i + 1)
entry_price = df.iloc[i + 1].Open  # Entry price is the Open price on the next row (i + 1)
```

Same for exit.

**Comment by russs123** [comment]
The 1 day offset already happens when the signal is generated:

>#entry is taken if the conditions were met at yesterday's close
df[f"{s}_Signal"] = (df.Low_7.shift(1) == True) & (df.Close.shift(1) > df.Slow_MA.shift(1))

This generates a signal today based conditions being met at yesterday's close. So then the trade is also entered today at the market open.
